log_json = false
log_level = "info,rbuilder=debug"
redacted_telemetry_server_port = 6061
redacted_telemetry_server_ip = "0.0.0.0"
full_telemetry_server_port = 6060
full_telemetry_server_ip = "0.0.0.0"

chain = "/network-configs/genesis.json"
reth_datadir = "/data/reth/execution-data/"
# We can have multiple, separated by comma
l2_reth_datadirs = ["/data/reth/gwyneth-167010"]

coinbase_secret_key = "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
relay_secret_key = "5eae315483f028b5cdd5d1090ff0c7618b18737ea9bf3c35047189db22835c48"
optimistic_relay_secret_key = "env:OPTIMISTIC_RELAY_SECRET_KEY"

# This shall be something like: "http://172.16.152.12:4000". To gather the correct IP, in (host machine) terminal we can query by: 
# docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' CL_CONTAINER_HASH
# but it is auto-filled from now by the taiko reth's 'make install' process
cl_node_url = [""]
jsonrpc_server_port = 9646
jsonrpc_server_ip = "0.0.0.0"
# Not exactly the same because the random postfix is generated every time, but something like: "/tmp/reth.ipc-3ZTH1DJ4"
el_node_ipc_path = "/tmp/reth.ipc"
# We can have multiple, separated by comma
l2_el_node_ipc_paths = ["/tmp/reth.ipc-167010"]
extra_data = "âš¡ðŸ¤–"

dry_run = false
dry_run_validation_url = "http://localhost:8545"

# blocks_processor_url can be an API service to record bids and transactions. It is not required.
# blocks_processor_url = "http://block_processor.internal"

ignore_cancellable_orders = true

sbundle_mergeabe_signers = []
# slot_delta_to_start_submits_ms is usually negative since we start bidding BEFORE the slot start
# slot_delta_to_start_submits_ms = -5000
live_builders = ["mp-ordering"]

# Currently the l1_rpc_url, l1_proposer_pk and l1_smart_contract_address are static. If we change smth on the smart contract "system" it might changes (depending on the deployment).
[[relays]]
name = "gwyneth"
url = "http://0xac6e77dfe25ecd6110b8e780608cce0dab71fdd5ebea22a16c0205200f2f8e2e3ad3b71d3499c54ad14d6c21b41a37ae@localhost:5555"
priority = 0
use_ssz_for_submit = false
use_gzip_for_submit = false
l1_rpc_url = "http://localhost:8545"
l1_proposer_pk = "39725efee3fb28614de3bacaffe4cc4bd8c436257e2c8bb887c4b5c4be45e76d"
l1_smart_contract_address = "0x9fCF7D13d10dEdF17d0f24C62f0cf4ED462f65b7"

[[builders]]
name = "mgp-ordering"
algo = "ordering-builder"
discard_txs = true
sorting = "mev-gas-price"
failed_order_retries = 1
drop_failed_orders = true

[[builders]]
name = "mp-ordering"
algo = "ordering-builder"
discard_txs = true
sorting = "max-profit"
failed_order_retries = 1
drop_failed_orders = true
